#!/usr/bin/env python3
"""
Generates offline audio clips for Maya's Spelling Garden and embeds them,
as base64 data URIs, into index.html (this repo's root — the exact file
GitHub Pages serves).

This script and its inputs (words.json, audio/) live inside the
maya-spelling-garden git repo on purpose, so the whole workflow works from
ANY fresh clone — including a Claude Code session on a phone. You do not
need the original Windows project folder to add a new week.

HOW TO ADD A NEW WEEK
----------------------
1. Open words.json (this repo's root) and append a new week object:
       {
         "id": "sept15",
         "label": "Sept 15",
         "focus": "Short Vowel o",
         "words": [
           { "word": "hop" },
           { "word": "dog", "emoji": "🐶" }
         ]
       }
   Only add "emoji" for words that have one clear, unambiguous picture
   (skip it for function/sight words like "am", "is", "at").
2. Rerun this script:
       python scripts/generate_audio.py
   It only generates audio for (word, voice) pairs that don't already have
   a cached mp3 in audio/ (so re-running after adding one new week is
   fast), then rewrites the WEEKS data block inside index.html with the
   full word list (old + new weeks) and freshly embedded audio for every
   voice.
3. Commit and push:
       git add -A
       git commit -m "Add <week label>"
       git push
   GitHub Pages redeploys automatically within ~30 seconds.

DOING THIS FROM A PHONE
------------------------
Open a Claude Code session (the claude.ai/code mobile web app, or the CLI
in a cloud sandbox) with this repo (github.com/jphan14/maya-spelling-garden)
cloned or open. Take a photo of the word sheet and send it in the chat —
Claude can read the words straight off the photo and edit words.json for
you. Then ask it to run this script and push. No desktop needed.

VOICES
------
Maya can tap alternate voice buttons to hear a word spoken differently.
The first entry in VOICES is the primary voice (auto-plays on word load);
the rest become tappable alt-voice buttons. To change voices, edit VOICES
below, delete the now-stale audio/*.mp3 files for the voice(s) you
changed (or just delete the whole audio/ folder to force a full
regenerate), and rerun this script.

Requires: pip install edge-tts
"""
import asyncio
import base64
import json
import os
import re
import sys

import edge_tts

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORDS_JSON = os.path.join(ROOT, "words.json")
AUDIO_DIR = os.path.join(ROOT, "audio")
HTML_PATH = os.path.join(ROOT, "index.html")

# Best-effort mirror into the original Windows project folder, if present
# (keeps Games/maya-spelling-garden.html in sync for local browsing there).
# Safe to ignore/fail — a fresh clone (e.g. on a phone) won't have this path.
LOCAL_MIRROR = os.path.join(
    os.path.dirname(ROOT), "Games", "maya-spelling-garden.html"
)

RATE = "-10%"  # slightly slowed down for a young reader

# Jenny-only: with 240 words, embedding 3 voices per word pushed the page to
# 11.8MB. Dropping to one voice keeps it around 4MB. The alt-voice buttons
# disappear automatically (the UI just renders however many voices are here)
# -- to bring them back for a smaller word list, uncomment below and rerun
# (their audio is already cached in audio/, this repo's history, from when
# they were generated, so no new TTS calls needed).
VOICES = [
    {"key": "jenny", "id": "en-US-JennyNeural", "label": "Jenny", "icon": "\U0001F469"},
    # {"key": "andrew", "id": "en-US-AndrewNeural", "label": "Andrew", "icon": "\U0001F9D1"},
    # {"key": "emma", "id": "en-US-EmmaNeural", "label": "Emma", "icon": "\U0001F467"},
]
PRIMARY_VOICE = VOICES[0]  # auto-plays on word load; all voices get an equal tap-to-hear button

START_MARKER = "/* WEEKS_DATA_START -- generated by scripts/generate_audio.py; edit words.json instead, then rerun the script */"
END_MARKER = "/* WEEKS_DATA_END */"


def load_words():
    with open(WORDS_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


def audio_path(word, voice_key):
    return os.path.join(AUDIO_DIR, "%s__%s.mp3" % (word, voice_key))


async def synth_one(word, voice_id, path):
    communicate = edge_tts.Communicate(word, voice_id, rate=RATE)
    await communicate.save(path)


CONCURRENCY = 12  # simultaneous edge-tts requests; keeps large word lists fast without hammering the service


async def generate_missing(all_words):
    os.makedirs(AUDIO_DIR, exist_ok=True)
    jobs = []
    for voice in VOICES:
        for word in all_words:
            path = audio_path(word, voice["key"])
            if not os.path.exists(path):
                jobs.append((word, voice, path))

    if not jobs:
        print("All %d word(s) x %d voice(s) already cached in %s" % (len(all_words), len(VOICES), AUDIO_DIR))
        return

    print("Generating %d audio clip(s) (up to %d at a time)..." % (len(jobs), CONCURRENCY))
    sem = asyncio.Semaphore(CONCURRENCY)
    done_count = [0]

    async def run_one(word, voice, path):
        async with sem:
            await synth_one(word, voice["id"], path)
            done_count[0] += 1
            print("  [%d/%d] wrote %s (%s)" % (done_count[0], len(jobs), os.path.basename(path), voice["label"]))

    await asyncio.gather(*[run_one(w, v, p) for w, v, p in jobs])


def b64_audio(word, voice_key):
    path = audio_path(word, voice_key)
    with open(path, "rb") as f:
        data = f.read()
    return "data:audio/mpeg;base64," + base64.b64encode(data).decode("ascii")


def js_string(s):
    return json.dumps(s)


def build_word_entry(w):
    entry = "{ word: %s" % js_string(w["word"])
    if w.get("emoji"):
        entry += ", emoji: %s" % js_string(w["emoji"])

    voice_parts = []
    for voice in VOICES:
        v_audio = b64_audio(w["word"], voice["key"])
        voice_parts.append("{ key: %s, label: %s, icon: %s, audio: %s }" % (
            js_string(voice["key"]), js_string(voice["label"]), js_string(voice["icon"]), js_string(v_audio)))
    entry += ", voices: [" + ", ".join(voice_parts) + "]"
    entry += " }"
    return entry


def build_weeks_js(weeks_data):
    lines = [START_MARKER, "var WEEKS = ["]
    for week in weeks_data["weeks"]:
        unit_part = (", unit: %d" % week["unit"]) if week.get("unit") is not None else ""
        lines.append("  { id: %s, label: %s%s, focus: %s, words: [" % (
            js_string(week["id"]), js_string(week["label"]), unit_part, js_string(week["focus"])))
        word_entries = [build_word_entry(w) for w in week["words"]]
        lines.append("    " + ",\n    ".join(word_entries))
        lines.append("  ] },")
    lines.append("];")
    lines.append(END_MARKER)
    return "\n".join(lines)


def inject_into_html(weeks_js, html_path):
    with open(html_path, "r", encoding="utf-8") as f:
        html = f.read()
    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(html):
        print("ERROR: could not find WEEKS_DATA markers in %s" % html_path, file=sys.stderr)
        sys.exit(1)
    new_html = pattern.sub(lambda m: weeks_js, html)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(new_html)
    size_mb = len(new_html.encode("utf-8")) / (1024 * 1024)
    print("Updated %s (%.2f MB)" % (html_path, size_mb))
    if size_mb > 5:
        print("WARNING: file size is over 5 MB -- consider fewer alt voices or a lower audio bitrate.")


def main():
    data = load_words()
    all_words = []
    seen = set()
    for week in data["weeks"]:
        for w in week["words"]:
            if w["word"] not in seen:
                seen.add(w["word"])
                all_words.append(w["word"])

    asyncio.run(generate_missing(all_words))
    weeks_js = build_weeks_js(data)
    inject_into_html(weeks_js, HTML_PATH)

    if os.path.exists(os.path.dirname(LOCAL_MIRROR)):
        try:
            with open(HTML_PATH, "r", encoding="utf-8") as f:
                full_html = f.read()
            with open(LOCAL_MIRROR, "w", encoding="utf-8") as f:
                f.write(full_html)
            print("Mirrored to %s" % LOCAL_MIRROR)
        except Exception as e:
            print("(skipped local mirror sync: %s)" % e)


if __name__ == "__main__":
    main()
